version: '3.4'

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/jenkins_data
  nexus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/nexus_data
  sonardata_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/data
  sonarconf_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/conf
  sonarlogs_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/logs
  sonardb_data:
     driver: local
     driver_opts:
       o: bind
       type: none
       device: /data/sonardb_data

services:
  nexus:
    build: ./nexus
    #image: sonatype/nexus3
    restart: always
    #ports:
    #  - "11000:8081"
    network_mode: "host"
    volumes:
      - nexus_data:/nexus-data
    environment:
      - NEXUS_CONTEXT=nexus
  jenkins:
    build: ./jenkins
    restart: always
    #ports:
    #  - "10000:8080"
    network_mode: "host"
    volumes:
      - jenkins_data:/var/jenkins_home/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
      - JENKINS_OPTS=--prefix=/jenkins --httpPort=10000
  sonardb:
    network_mode: "host"
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  sonar:
    image: sonarqube
    restart: always
    command: -Dsonar.web.context=/sonar
    ports:
     - "12000:9000"
     - "9092:9092"
    network_mode: "host"
    depends_on:
      - sonardb
    volumes:
      - sonarconf_data:/opt/sonarqube/conf
      - sonarlogs_data:/opt/sonarqube/logs
      - sonardata_data:/opt/sonarqube/data
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar

