version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/jenkins_data
  nexus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/nexus_data
  sonardata_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/data
  sonarconf_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/conf
  sonarlogs_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/sonar_data/logs
  sonardb_data:
     driver: local
     driver_opts:
       o: bind
       type: none
       device: /data/sonardb_data

services:
  nexus:
    build: ./nexus
    restart: always
    ports:
      - "11000:8081"
    networks:
      - prodnetwork
    volumes:
      - nexus_data:/nexus-data
    environment:
      - NEXUS_CONTEXT=nexus
  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "10000:8080"
    networks:
      - prodnetwork
    volumes:
      - jenkins_data:/var/jenkins_home/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
      - JENKINS_OPTS=--prefix=/jenkins  
  sonardb:
    networks:
      - prodnetwork
    restart: always
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - sonardb_data:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar
  sonar:
    image: sonarqube
    restart: always
    command: -Dsonar.web.context=/sonar
    ports:
     - "12000:9000"
     - "9092:9092"
    networks:
      - prodnetwork
    depends_on:
      - sonardb
    volumes:
      - sonarconf_data:/opt/sonarqube/conf
      - sonarlogs_data:/opt/sonarqube/logs
      - sonardata_data:/opt/sonarqube/data
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar

##########################################################################################
# DISABLED: GitLab takes too much memory and CPU. Demo uses GitHub repositories instead.
#
#  gitlab:
#    image: gitlab/gitlab-ce:latest
#    restart: always
#    networks:
#      - prodnetwork
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        # external_url 'https://gitlab.example.com'
#        # Add any other gitlab.rb configuration here, each on its own line
#    ports:
#      - "10080:80"
#      - "10443:443"
#      - "10022:22"
#    volumes:
#      - /opt/gitlab/config:/etc/gitlab
#      - /opt/gitlab/logs:/var/log/gitlab
#      - /opt/gitlab/data:/var/opt/gitlab
